<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Jhu\ZdtLoggerModule\Options\ModuleOptions'               => __DIR__ . '/src/Jhu/ZdtLoggerModule/Options/ModuleOptions.php',
    'Jhu\ZdtLoggerModule\Writer\Stack'                        => __DIR__ . '/src/Jhu/ZdtLoggerModule/Writer/Stack.php',
    'Jhu\ZdtLoggerModule\Collector\ZendWriterCollector'       => __DIR__ . '/src/Jhu/ZdtLoggerModule/Collector/ZendWriterCollector.php',
    'Jhu\ZdtLoggerModule\Module'                              => __DIR__ . '/src/Jhu/ZdtLoggerModule/Module.php',
    'Jhu\ZdtLoggerModule\ServiceFactory\ModuleOptionsFactory' => __DIR__ . '/src/Jhu/ZdtLoggerModule/ServiceFactory/ModuleOptionsFactory.php',
    'Jhu\ZdtLoggerModule\ServiceFactory\LoggerFactory'        => __DIR__ . '/src/Jhu/ZdtLoggerModule/ServiceFactory/LoggerFactory.php',
    'Jhu\ZdtLoggerModule\ServiceFactory\CollectorFactory'     => __DIR__ . '/src/Jhu/ZdtLoggerModule/ServiceFactory/CollectorFactory.php',
);